modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${mod_issues_page}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = "${mod_description}"
displayURL = "${mod_homepage}"
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sinocore"
type = "required"
versionRange = "${neoforge_sinocore_version_range}"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vanillacream.mixins.json"

[[mixins]]
config = "vanillacream-neoforge.mixins.json"
